import fs from 'node:fs';
import path from 'node:path';

const root=path.resolve(import.meta.dirname,'..');
const cue=(asset,anchor,w,h,duration,more={})=>({asset,start:0,duration,anchor,w,h,x:0,y:0,alpha:1,scaleFrom:.82,scaleTo:1,dx:0,dy:0,rotation:0,spin:0,envelope:'pulse',...more});
const entries={};
const event=(id,cues,stopTags=[])=>{entries[id]={cues,...(stopTags.length?{stopTags}:{})};};
event('LianzhuJian.Cast',[cue('LianzhuJian.Cast','Caster_WeaponPoint',235,235,.13)]);
event('LianzhuJian.Shot',[cue('LianzhuJian.Projectile','Attack_MidPoint',465,154,.16,{scaleFrom:.8,dx:110,tag:'volley-arrow'})]);
for(let n=1;n<=4;n++)event(`LianzhuJian.Hit${n}`,[cue('LianzhuJian.Hit','Target_HitPoint',155,155,.16,{x:(n-2.5)*22,y:n%2? -13:13}),cue('LianzhuJian.End','Target_HitPoint',105,105,.18,{x:(n-2.5)*22,alpha:.52})]);
event('ChuanyunJian.Cast',[cue('ChuanyunJian.Cast','Caster_WeaponPoint',265,265,.2)]);
event('ChuanyunJian.Shot',[cue('ChuanyunJian.Projectile','Attack_MidPoint',620,206,.2,{dx:140,tag:'heavy-arrow'})]);
event('ChuanyunJian.Hit',[cue('ChuanyunJian.AirCone','Target_HitPoint',405,240,.17,{scaleFrom:.45,scaleTo:1.15}),cue('ChuanyunJian.Hit','Target_HitPoint',250,250,.25),cue('ChuanyunJian.End','Target_HitPoint',275,130,.23,{start:.07,alpha:.55})]);
event('TuishenJian.Cast',[cue('TuishenJian.Cast','Caster_WeaponPoint',225,195,.16)]);
event('TuishenJian.Shot',[cue('TuishenJian.Projectile','Attack_MidPoint',380,127,.18,{dx:100})]);
event('TuishenJian.Hit',[cue('TuishenJian.Hit','Target_HitPoint',170,170,.18)]);
event('TuishenJian.RetreatSuccess',[cue('TuishenJian.Retreat','Caster_PassivePoint',335,335,.25,{dx:-45}),cue('TuishenJian.End','Caster_PassivePoint',230,115,.18,{start:.13,alpha:.45})]);
event('TuishenJian.RetreatBlocked',[cue('TuishenJian.Blocked','Caster_PassivePoint',290,290,.16,{dx:-15})]);
event('DingshenJian.Cast',[cue('DingshenJian.Cast','Caster_WeaponPoint',205,205,.15)]);
event('DingshenJian.Shot',[cue('DingshenJian.Projectile','Attack_MidPoint',360,120,.18,{dx:90})]);
event('DingshenJian.Hit',[cue('DingshenJian.Hit','Target_HitPoint',165,165,.19)]);
event('DingshenJian.Apply',[cue('DingshenJian.Trigger','Target_FeetPoint',210,160,.25),cue('DingshenJian.Active','Target_FeetPoint',165,115,1,{start:.2,alpha:.34,loop:true,tag:'bind-status'})]);
event('DingshenJian.CostPulse',[cue('DingshenJian.CostPulse','Target_FeetPoint',205,155,.22)]);
event('DingshenJian.Expire',[cue('DingshenJian.End','Target_FeetPoint',175,115,.2)],['bind-status']);
event('XiaoLiGuang.EnterFar',[cue('XiaoLiGuang.Trigger','Target_HitPoint',210,210,.26),cue('XiaoLiGuang.Active','Caster_WeaponPoint',125,125,1,{start:.12,alpha:.34,loop:true,tag:'far-passive'})]);
event('XiaoLiGuang.LeaveFar',[cue('XiaoLiGuang.Deactivate','Caster_WeaponPoint',135,135,.22)],['far-passive']);
const library={version:1,events:entries};
fs.mkdirSync(path.join(root,'Cocos'),{recursive:true});
fs.writeFileSync(path.join(root,'Cocos/vfx-events.json'),JSON.stringify(library,null,2));
fs.mkdirSync(path.join(root,'preview'),{recursive:true});
fs.writeFileSync(path.join(root,'preview/data.js'),`window.HR_MANIFEST=${JSON.stringify(JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8')))};\nwindow.HR_EVENTS=${JSON.stringify(library)};\n`);
console.log(JSON.stringify({events:Object.keys(entries).length}));
